Fix #429 line break for global note
4minitz/4minitz pull request #462
Opened 2018-09-10 13:24 UTC by be41zehe

2018-09-11 04:02 UTC, migerh commented
The acceptance criteria from #429:

- [x] Field should be initially 2 lines in height
- [x] Pressing ENTER in this field will add a line
- [x] If user adds more lines, the hight should increase
- [ ] Line breaks should be preserved in: browser, eMail and generated PDFs, finalized meetings
- [x] TAB should allow to leave field. Latests in this case changes shall be stored to database (and be propagated to other connected users)

Only partially checked line break preservation. They are preserved after leaving the editor as well as after finalization. But there are no line breaks in the generated HTML:

![image](https://user-images.githubusercontent.com/368715/45337403-1a867800-b588-11e8-8b72-74dc33aa6b89.png)

Unable to check: Line breaks in mails and generated pdfs.

2018-09-11 04:03 UTC, migerh requested changes

2018-09-11 04:03 UTC, migerh commented on client/templates/minutes/minutesedit.js
> +        console.log("fdv");
Please remove this.

2018-09-11 19:11 UTC, migerh approved these changes

2018-09-25 05:57 UTC, derwok commented
Hi,
I think the feature looks already quite good! Will be very useful for users.
Three points:

1. I think we should define a maximum height for this field. Let's make it "big" enough that usual use cases need no scrolling - but small enough that if someone pastes the Wikipedia in here, that scrolling will not be endless. So, may I add one more acceptance criteria: Lets make the maximum heigth something like `700 px`.

1. My second point is - as Michael already commented - if I freshly enter a minute with a long note, The initial height is static (2 lines), but it should also be dynamic

1. If a second user (role: Invited) views the minutes (hint: use a different browser for testing!) this user will only see 2 lines height - always! With no chance to edit something, this will never change. If the point above is solved, this problem will be smaller (user might press RELOAD to get correct height). But Premium solution would be if the "Invited" users gets correct height even if the content of the note changes by moderator while invited user is passively viewing.

2018-11-13 21:13 UTC, derwok commented
We chose the "green" one.

2018-11-13 21:13 UTC, closed without merging